### PR TITLE
Fixed a few TODOs

### PR DESCRIPTION
**Pull request by FFinotello**

### CODE REVIEW

**Comment by federicomarini** [comment]
Any idea what the "conflicts" should be? To me they look pretty similar - is it some weird misinterpretation of whitespaces and git is complaining?

**Comment by federicomarini** [comment]
Seems it is not just about the final line ending - the web editor seems still to be annoyed.
Thanks for the tip, still @grst

**Comment by grst** [comment]
running `dos2unix` did the trick. For future PRs the `.gitattributes` should indeed solve that (at least when using a local git client, not sure about the web editor)

**Comment by federicomarini** [comment]
Got it, thanks a lot!
I'm normally bouncing among unix machines, so I never encountered that issue.
F

**Pull request merged**
